### ISSUE TITLE
Wrong len for locations with non-latin characters

### ISSUE THREAD

**Issue by DmitrySandalov** [vlevit/transmission-batch-move#3]
1. Set location as
`/some/destination/folder/Проверка`
2. Launch `transmission-batch-move`
`transmission-batch-move --path=/var/lib/transmission-daemon/info destination destination2`

Expected: new location is `/some/destination2/folder/Проверка`

Observed: location is set as `/some/destination2/folder/Про`

**Comment by vlevit** [comment]
@DmitrySandalov 
Hi! Thanks for the report. Can you please test a fix?
https://github.com/vlevit/transmission-batch-move/blob/fix-non-ascii-destination/transmission-batch-move

**Comment by vlevit** [comment]
Fix merged.

**Comment by rufoa** [comment]
I think this fix breaks latin characters! New count seems to be off-by-one

NB:
```
$ expr length "hello"
5

$ wc -c <<< "hello"
6
```

**Comment by rufoa** [comment]
Possible fix:

```
echo -n "hello" | wc -c
5
```

Also works correctly on non-latin:

```
echo -n "Привет" | wc -c
12
```

**Comment by vlevit** [comment]
@rufoa Thanks Rufus! I pushed your suggested fix to master. Can you please confirm it is working for you?

**Comment by rufoa** [comment]
Yes, the code in master now works for both latin and non-latin paths :+1: 

Thank you for publishing this script! It saved me a lot of time.

**Comment by vlevit** [comment]
@rufoa And thank you for investigating and reporting the issue!
