### ISSUE TITLE
always fails with a number before path

### ISSUE THREAD

**Issue by dchmelik** [vlevit/transmission-batch-move#8]
I'd like to use it and tried like 'transmission-batch-move \\/home\\user\\/directoryA \\/home\\/user/\\directoryB'.
Though most (hundreds) torrents are in directoryA the script always failed with similar error messages.
It always said (for a two-digit number n) "tail: cannot open 'n' for reading: No such file or directory".
I saw the particular .resume files have path after 'n:' in format n:/home/user/directoryA (I checked several, all matching this format).

**Comment by chrisjantzen** [comment]
I ran into this issue too and realized tail is reading the old length as the filename. By simply adding a - in front of it, it reads it correctly. See this pull request: https://github.com/vlevit/transmission-batch-move/pull/9

**Comment by dchmelik** [comment]
Thanks; worked, but this should stay open until merged.

**Comment by vlevit** [comment]
PR was merged. Sorry for not actively maintaining the project. If anyone is willing to help with maintaince please let me know.
